repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v17.0.6
    hooks:
      - id: clang-format
        args: [--style=file]
        files: \.(cpp|hpp)$

  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.0
    hooks:
      - id: clang-tidy
        args: [-p=build]
        files: \.(cpp|hpp)$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
